### ISSUE TITLE
baseUrl use  a CDN path  prerender-spa doesn't work

### ISSUE THREAD

**Issue by itboos** [SolarLiner/vue-cli-plugin-prerender-spa#15]
### use vue-cli 3 
    Here's the vue.config.js I'm using:
```javascript
   {
     ...
     baseUrl: process.env.NODE_ENV === 'production'
           ? 'https://js.mycdnhost.com/web/'
            : '/',
   }
```

When our Project release，our index.html file will in   www.a.com,  but out our js、css file  we want use cdn server to improve experience, but when the baseUrl  use a CDN path,  vue-cli-plugin-prerender-spa d donesn't work, and it donesn't  show any error. 

And if the baseUrl: '/'  , It works well， what  should  I do?    I think is is a common case to do that, which js, css in a CDN server,  index.html in another server.  Someone encountered in this situation like me ? 

Any help would be appreciated.

**Comment by itboos** [comment]
> Is it just the not-prerendered HTML
 Is it just the not-prerendered HTML, just like normal vue SPA build files, it looks like this:
![image](https://user-images.githubusercontent.com/21290640/50578328-a42dbe80-0e73-11e9-8661-d9b9f9c4828a.png)

**Comment by SolarLiner** [comment]
After trying to resolve this issue, I'm quite confident this can't easily be covered by this plugin. When you set the baseUrl to an external URL, you tell browsers to look outside the server that is set by the pre-rendering plugin. Maybe there's a way to control Chrome to map your external URLs back into internal ones; or maybe the JSDOM renderer would work.

In any case, for now, I don't see a way to implement your use-case, sorry.

**Comment by SolarLiner** [comment]
Check out version 1.1.0, you can hook into Puppeteer's `postProcess` function. Maybe you can replace the paths this way.

**Comment by itboos** [comment]
> Check out version 1.1.0, you can hook into Puppeteer's `postProcess` function. Maybe you can replace the paths this way.
The Puppeteer's postProcess function can deal the html files, but the CDN path is not only  appear in .html file ,  but also in app.js , only replace the html file will have Problem.

**Comment by SolarLiner** [comment]
Ah that's right, sorry.

If that two-step solution is working okay for you, maybe we can start a "cookbook" wiki entry for those.

In the mean time, this seems to be out of my control; you can maybe try to contact the Puppeteer team to have their input in the problem.

**Comment by itboos** [comment]
I think you can start a 'cookbook' wiki entry for those who use CDN path, I don't have the permission
