### ISSUE TITLE
Fix error handling

### ISSUE THREAD

**Issue by EvodiaAut** [SolarLiner/vue-cli-plugin-prerender-spa#17]
**Describe the bug**

Error message on run
```
node_modules/vue-cli-plugin-prerender-spa/index.js:101
  } catch {
          ^

SyntaxError: Unexpected token {
```

Can you add in [Line index.js:101](https://github.com/SolarLiner/vue-cli-plugin-prerender-spa/blob/develop/index.js#L101) a exception parameter? [_Informations_](https://www.joyent.com/node-js/production/design/errors) 

from
```
} catch { <-------
  if (existsSync(oldConfigPath)) {
    options = JSON.parse(readFileSync(oldConfigPath).toString("utf-8"));
  }
}
```

to
```
} catch(ex) { <-------
  if (existsSync(oldConfigPath)) {
    options = JSON.parse(readFileSync(oldConfigPath).toString("utf-8"));
  }
}
```
**Additional context**
Package version: 1.1.1
Vue version: 2.5.21
Vue CLI version: 3.3.0

**Comment by EvodiaAut** [comment]
I get this error on node version v8.15.0 
In node version v10.x is works perfectly

**Comment by SolarLiner** [comment]
Hotfix uploaded to npm as v1.1.2, thanks for the notice!
