### ISSUE TITLE
Plugin vue-cli-plugin-prerender-spa does not have a generator to invoke .I reported an error during installation.

### ISSUE THREAD

**Issue by lee134134134** [SolarLiner/vue-cli-plugin-prerender-spa#20]
**Describe the bug**
Plugin vue-cli-plugin-prerender-spa does not have a generator to invoke .I reported an error during installation.So，there is no way to build the page correctly when you build it again.

**To Reproduce**
1. vue add prerender-spa
2. yarn build

<img width="563" alt="2019-01-18 5 12 29" src="https://user-images.githubusercontent.com/4250254/51377145-1aeddb80-1b45-11e9-9a2e-fd3cbd6854a3.png">
<img width="646" alt="2019-01-18 5 17 48" src="https://user-images.githubusercontent.com/4250254/51377132-13c6cd80-1b45-11e9-89a2-f33fd4868608.png">

**Additional context**
Package version: 1.1.3
Vue version: 2.5.21
Vue CLI version: 3.3.0

**Comment by shredding** [comment]
I have this as well, is there a way to still get going?

**Comment by ellefsen** [comment]
@shredding

If you add the .prerender-spa.json file manually and include the dispatchEvent mounted action in main.js I was able to build my project with prerendering.

Add line 5 to main.js.
```
new Vue({
  router,
  store,
  render: h => h(App),
  mounted: () => document.dispatchEvent(new Event('x-app-rendered'))
}).$mount("#app")
```

.prerender-spa.json example in root.
```
{"renderRoutes":["/","/foo","/bar"],"useRenderEvent":true,"headless":true,"onlyProduction":true}
```

**Comment by SolarLiner** [comment]
Actually you should create a `prerenderSpa` config inside `vue.config.js` (the old .prerender-spa.json is being deprecated, new versions of the plugin should convert it automatically when building the project).

As for the generator not being provided, it was the stupidest cause of all: it was being ignored when packing the tarball. :man_facepalming:

**Comment by Uninen** [comment]
I still ran into this with version 1.1.4 (Vue 2.6.6, vue-cli 3.4.0):

<img width="503" alt="screen shot 2019-02-15 at 15 34 48" src="https://user-images.githubusercontent.com/43100/52860187-67720a00-3137-11e9-9bec-dd67765084fa.png">

**Comment by SolarLiner** [comment]
I cannot reproduce. Packaging includes the generator file and installing the tarball before invoking the plugin works as expected.

**Comment by Timibadass** [comment]
@SolarLiner, i also encountered that issue on 1.1.4

**Comment by ousmaneNdiaye** [comment]
I had the same problem trying to install trough terminal but it works trough the vue-cli UI ( running ```vue ui```).

**Comment by SolarLiner** [comment]
So the problem is that the version uploaded to npm doesn't contain the `generator.js` function, which is weird because that was the problem for an earlier problem. Before uploading this version I double checked the tarball to confirm the generator file was there.

Master also generate correct tarballs that, installed in a test repo, do invoke the generator (because it is present in the package).

**Comment by karticus** [comment]
Is this as simple as the files spec in package.json not having js suffix for generator?

```
"files": [
    "index.js",
    "prompts.js",
    "generator",  // => "generator.js"
    "README.md",
    "LICENSE"
  ],
```

**Comment by SolarLiner** [comment]
@karticus You've hit the jackpot. I have search everywhere _in_ the code, and not _around_ it. :man_facepalming:
