### ISSUE TITLE
Add 'skipThirdPartyRequests' as an option

### ISSUE THREAD

**Issue by acidhorse** [SolarLiner/vue-cli-plugin-prerender-spa#28]
When using this plugin (vs the prerender-spa-plugin directly) I would like the ability to skip 3rd party requests as an option during setup

**Comment by SolarLiner** [comment]
You can configure the renderer directly through the `customRendererOptions` in the plugin configuration. It will override any other options passed internally and be sent to the Puppeteer renderer.
