### ISSUE TITLE
Advert processing

### ISSUE THREAD

**Issue by jamiecarter7** [SolarLiner/vue-cli-plugin-prerender-spa#32]
** NOT A FEATURE / BUG **

Has anyone got any experience with how to pre-render an SPA with adverts that appear on said pages?

When building on my local google sees that I am on localhost so an advert is not delivered, but I am worried that rendering the 300 or so pages on my spa might trigger large amounts of ad impressions. 

How have other people tackled this issue? 

Thanks!

**Comment by chrillefkr** [comment]
Inject a `window.property` when pre-rendering, and do a `v-if="!prerendering"` around your adverts. That way they won't be rendered during pre-render.

https://github.com/chrisvfritz/prerender-spa-plugin#prerendererrenderer-jsdom-options

```
// vue.config.js
module.exports = {
  prerenderSpa: {
    customRendererConfig: {
      injectProperty: '__PRERENDER_INJECTED',
      inject: {
        foo: 'bar'
      },
    },
    // other options
  }
}
```

```
// Example.vue
<template>
<div class="Example">
  <span v-if="prerendering">This will only be visible during pre-render.</span>
</div>
</template>
<script>
export default {
  data(){
    return {
      prerendering: Boolean(window.__PRERENDER_INJECTED),
    }
  },
}
</script>
```

**Comment by SolarLiner** [comment]
Thanks @chrillefkr, closing this as non-issue.
