### ISSUE TITLE
Asynchronously loaded content not rendering

### ISSUE THREAD

**Issue by mihajlon97** [SolarLiner/vue-cli-plugin-prerender-spa#39]
**Route which loads content from some API on the mounted hook should be able to prerender that async content.**
Right now not working.
Current confing in vue.config.js
```
pluginOptions: {
    prerenderSpa: {
      registry: undefined,
      renderRoutes: [
      	'/page-with-async-content-load-on-mounted-hook',
        '/'
      ],
      useRenderEvent: true,
      headless: true,
      onlyProduction: true,
	    renderAfterTime: 5000
    }
  },
```

Thanks in advance!

**Comment by mihajlon97** [comment]
Solved :)
 
async mounted() {
	      axios.get('EXTERNAL_API_URL')
			    .then((response) => {
				    if(response.status === 200) {
				        console.log(response.data);
				        this.result = response.data;
				    }
			      **document.dispatchEvent(new Event('x-app-rendered'))**
			    });
}

**Comment by SolarLiner** [comment]
Yup! By default the plugin triggers sending an event when the root Vue component finishes rendering - this obviously doesn't take into account any async code that might still be running. You can remove the `mounted` event in the root Vue component (that the plugin added) to prevent it from firing the event, and instead fire it whenever you want.
