### ISSUE TITLE
No prerender when baseURL variable is set in vue.config.js

### ISSUE THREAD

**Issue by madjidtaha** [SolarLiner/vue-cli-plugin-prerender-spa#6]
**Describe the bug**
No prerender are triggered when baseURL variable is set. Build is created as normal as when the plugin is not installed but the console keeps waiting on the sentence "Building for production"

**To Reproduce**
1. `vue create example`
2. `cd example`
3. `vue add prerender-spa`
4. Create a `vue.config.js` file in the root of the project
5. Fill `vue.config.js` with this.
```javascript
module.exports = {
  baseUrl: '/example/',
}; 
```
6. `npm run build`

**Expected behavior**
Build the project and prerender the project with the correct url

**Additional context**
Package version: 1.0.2
Vue version: 2.5.17
Vue CLI version: 3.0.1

**Comment by SolarLiner** [comment]
Currently, you'd need to specify the URLs with the Base URL into the array of pages to pre-render. I'd need to somehow be able to get the base URL from the configuration to update the routes array.
I'd need to dig into the docs again to see if the configuration files do provide it, otherwise, I'd need to parse the files - which means I'd need to set up an actual parser for this and other issues.

**Comment by madjidtaha** [comment]
I just tried again with `headless: false` and with the same route as the baseURL,

I don't know which server is used to mount the build to allow Puppeter to prerender the page but it seems that this server did not mount the folder on the baseURL so, that's why it cannot access to the assets.

I join some screenshot, it might be helpful.

Thanks for your help
<img width="1312" alt="screen shot 2018-09-25 at 01 48 56" src="https://user-images.githubusercontent.com/1833954/45985166-46642c00-c065-11e8-9bf7-00d193fabc7d.png">
<img width="1312" alt="screen shot 2018-09-25 at 01 42 20" src="https://user-images.githubusercontent.com/1833954/45985170-4c5a0d00-c065-11e8-8741-e329ca2aeec7.png">
<img width="1312" alt="screen shot 2018-09-25 at 01 42 21" src="https://user-images.githubusercontent.com/1833954/45985176-511ec100-c065-11e8-916b-ef13739b0de2.png">

**Comment by jpicton** [comment]
Cheers! The hotfix works like a charm. 👍
