### ISSUE TITLE
Meta Information

### ISSUE THREAD

**Issue by deathlynocturnal** [SolarLiner/vue-cli-plugin-prerender-spa#69]
**Is your feature request related to a problem? Please describe.**
No way to add more SEO friendly meta tags and information to the page? Currently using: https://www.npmjs.com/package/@bachdgvn/vue-router-meta-tags

**Describe the solution you'd like**
I am not sure if this is a feature specifically or support for something, but since Vue CLI now does not use webpack (or at least allows us to edit the webpack config), I was wondering is there any plugins that would allow me to define meta information within the routes and then this would then amend and edit the meta tags before the snapshot is taken?

**Describe alternatives you've considered**
I have found things like this: https://www.npmjs.com/package/@bachdgvn/vue-router-meta-tags but they do not work with this plugin.

**Additional context**
Any other plugins that do exist and work please let me know!

Thanks,

**Comment by demiro** [comment]
yes, this is very much needed.... if I defined meta property within my router... it is not displayed in my pre-rendered page

**Comment by rameshlohala** [comment]
Try using vue-mata package: https://www.npmjs.com/package/vue-meta.
