### ISSUE TITLE
As soon as I pack it, I'm going to report the following error, and then I'm going to keep compiling

### ISSUE THREAD

**Issue by sandaoliuhzw** [SolarLiner/vue-cli-plugin-prerender-spa#7]
![default](https://user-images.githubusercontent.com/28532461/46062720-35b6d180-c19d-11e8-9166-4be4b60da734.jpg)
I just installed it and packed it, and that's it

**Comment by sandaoliuhzw** [comment]
Big brother, can you put all the steps of use one by one?As well as some common problems, the current use is really dizzy, stuck for too long

**Comment by SolarLiner** [comment]
Did you follow the advice given by the error? This plugin needs an embedded Chrome instance to render the pages into. It is installed when you invoke the plugin normally, but I guess in your case the download didn't go through for some reason.

Try doing `npm install` or `yarn install` depending on the package manager you want to use to refresh the packages and retrigger the download of the plugin.

**Comment by sandaoliuhzw** [comment]
É um problema de download. Agora está resolvido.
